#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
  echo "[ERROR] Aborting commit. Your commit message is invalid. Use conveventional commits!" >&2
  exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,100}$"; then
  echo "[ERROR] Aborting commit. Your commit message is too long." >&2
  exit 1
fi
