name: CI/CD API BFF

on:
  push:
    branches: ["main"]
    paths: ["api/**"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::571600868208:role/InfrastructureStack-spaprodspaprodwebappdeploymentd-lIAmGiNZma2n
          role-session-name: GithubActionDeployWebappSession

      - name: Verify AWS Account
        run: aws sts get-caller-identity

      - name: check environment
        run: env | sort

      - name: add aws account id to env
        run: |
          echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: check environment again
        run: env | sort

      - name: Deploy and Restart App
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" &&
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "[{\"Key\":\"InstanceIds\",\"Values\":[\"i-0e2a2fed9b970db6c\"]}]" \
            --parameters "commands=['sudo cd ~/xpensemngr/api && sudo git pull && sudo npm ci && sudo pm2 restart the-app-2']" \
            --region eu-central-1
            --debug
