name: CI/CD API BFF

on:
  push:
    branches: ["main"]
    paths: ["api/**"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::571600868208:role/InfrastructureStack-spaprodspaprodwebappdeploymentd-lIAmGiNZma2n
          role-session-name: GithubActionDeployWebappSession

      - name: Verify AWS Account
        run: aws sts get-caller-identity
      - name: Deploy and Restart App
        env:
          EC2_INSTANCE_NAME: xpm-ec2-main-api-prod
          NODE_PATH: /root/.nvm/versions/node/v20.12.2/bin
          HOME_DIR: /root
        run: |
          aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "[{\"Key\":\"tag:Name\",\"Values\":[\"$EC2_INSTANCE_NAME\"]}]" \
          --parameters "commands=[\"export HOME=$HOME_DIR && export PATH=$NODE_PATH:$PATH && cd /root/xpensemngr/api && git pull && npm ci && pm2 list && pm2 restart xpm-api-bff\"]" \
          --timeout-seconds 300
